name: Developer Hub
markdown: kramdown
highlighter: pygments
safe: true
baseurl: /openFEC-documentation
exclude: ['.ruby-version', 'node_modules', 'package.json', 'bower.json']
sass:
  sass_dir: static/_sass

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      organization-name: "openFEC"
      organization-url: "http:///fec.18f.us"
      organization-email: user@agency.gov
      source-code-policy.url:
